FROM node:14
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
# RUN npm ci --only=production
COPY babel.config.json .
COPY webpack.config.js .
COPY src src
EXPOSE 3000
CMD ["npm", "run", "app:dev"]
