version: '3.9'
services:
    app:
        build:
            context: ../.
            dockerfile: docker/app/dev.Dockerfile
        image: iamkevinlowe/elastic-movies_app
        container_name: elastic-movies_app
        env_file:
            - ../env/app.dev.env
        networks:
            - elastic-movies
        volumes:
            - ../app:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '8000:8000'

    worker:
        build:
            context: ../.
            dockerfile: docker/worker/dev.Dockerfile
        image: iamkevinlowe/elastic-movies_worker
        container_name: elastic-movies_worker
        env_file:
            - ../env/worker.dev.env
        networks:
            - elastic-movies
        volumes:
            - ../app:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - redis

    kibana:
        image: kibana:7.10.1
        container_name: elastic-movies_kibana
        environment:
            ELASTICSEARCH_HOSTS: http://kevinlowe.asuscomm.com:9200
            ELASTICSEARCH_USERNAME: kibana_system
            ELASTICSEARCH_PASSWORD: 3lastic
        restart: on-failure
        ports:
            - '5601:5601'

    redis:
        image: redis:latest
        container_name: elastic-movies_redis
        restart: on-failure
        networks:
            - elastic-movies
        volumes:
            - dataRedis:/data

networks:
    elastic-movies:
        driver: bridge

volumes:
    dataRedis:
        driver: local
