version: '3.9'
services:
    app:
        build:
            context: ../.
            dockerfile: docker/app/Dockerfile
        image: iamkevinlowe/elastic-movies_app
        container_name: elastic-movies_app
        env_file:
            - ../env/app.env
        volumes:
            - ../app:/usr/src/app
            - web-root:/usr/src/app/dist
        networks:
            - app-network

    worker:
        build:
            context: ../.
            dockerfile: docker/worker/Dockerfile
        image: iamkevinlowe/elastic-movies_worker
        container_name: elastic-movies_worker
        env_file:
            - ../env/worker.env
        volumes:
            - ../app:/usr/src/worker
        ports:
            - '9000:9000'
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: elastic-movies_redis
        restart: on-failure
        volumes:
            - dataRedis:/data

volumes:
    dataRedis:
        driver: local
