version: '3.9'
services:
    app:
        build:
            context: ../.
            dockerfile: docker/app/Dockerfile
        image: iamkevinlowe/elastic-movies_app
        container_name: elastic-movies_app
        env_file:
            - ../env/app.env
        networks:
            - elastic-movies
        volumes:
            - ../app:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '80:80'

    worker:
        build:
            context: ../.
            dockerfile: docker/worker/Dockerfile
        image: iamkevinlowe/elastic-movies_worker
        container_name: elastic-movies_worker
        env_file:
            - ../env/worker.env
        networks:
            - elastic-movies
        volumes:
            - ../app:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: elastic-movies_redis
        restart: on-failure
        networks:
            - elastic-movies
        volumes:
            - dataRedis:/data

networks:
    elastic-movies:
        driver: bridge

volumes:
    dataRedis:
        driver: local
