version: '3.9'
services:
    app:
        build:
            context: ../.
            dockerfile: docker/app/Dockerfile
        image: iamkevinlowe/elastic-movies_app
        container_name: elastic-movies_app
        env_file:
            - ../env/app.env
        volumes:
            - ../app:/usr/src/app
            - web-root:/usr/src/app/dist
        networks:
            - app-network

    server:
        image: nginx:mainline-alpine
        container_name: elastic-movies_server
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - web-root:/var/www/html
            - ../nginx-conf:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        depends_on:
            - app
        networks:
            - app-network

    certbot:
        image: certbot/certbot
        container_name: elastic-movies_certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - app
        command: certonly --webroot --webroot-path=/var/www/html --email iamkevinlowe@gmail.com --agree-tos --no-eff-email --staging -d elastic-movies.com -d www.elastic-movies.com

    worker:
        build:
            context: ../.
            dockerfile: docker/worker/Dockerfile
        image: iamkevinlowe/elastic-movies_worker
        container_name: elastic-movies_worker
        env_file:
            - ../env/worker.env
        volumes:
            - ../app:/usr/src/worker
        ports:
            - '9000:9000'
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: elastic-movies_redis
        restart: on-failure
        volumes:
            - dataRedis:/data

volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: app/dist/
            o: bind
    dataRedis:
        driver: local

networks:
    app-network:
        driver: bridge
