version: '3.9'
services:
    app:
        build:
            context: ../.
            dockerfile: docker/app/dev.Dockerfile
        image: iamkevinlowe/elastic-movies_app
        container_name: elastic-movies_app
        env_file:
            - ../env/app.dev.env
        volumes:
            - ../app:/usr/src/app
        ports:
            - '8000:8000'

    worker:
        build:
            context: ../.
            dockerfile: docker/worker/dev.Dockerfile
        image: iamkevinlowe/elastic-movies_worker
        container_name: elastic-movies_worker
        env_file:
            - ../env/worker.dev.env
        volumes:
            - ../app:/usr/src/worker
        ports:
            - '9000:9000'
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: elastic-movies_redis
        restart: on-failure
        volumes:
            - dataRedis:/data

volumes:
    dataRedis:
        driver: local
