name: build

on:
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
      
#           - name: Use Node.js 14.15.3
#             uses: actions/setup-node@v1
#             with:
#               node-version: '14.15.3'
#
#           - name: Install npm and run unittest
#             run: |
#               npm install
#               npm run test
#             env:
#               CI: true

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            -   name: Build and push app
                id: docker_build_app
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./docker/app/Dockerfile
                    push: true
                    tags: iamkevinlowe/elastic-movies_app:latest

            -   name: App image digest
                run: echo ${{ steps.docker_build.outputs.digest }}

            -   name: Build and push worker
                id: docker_build_worker
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./docker/worker/Dockerfile
                    push: true
                    tags: iamkevinlowe/elastic-movies_worker:latest

            -   name: Worker image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
